import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { InMemoryTransport } from '@modelcontextprotocol/sdk/inMemory.js';
import { initLedger, record, getById, loadAll, type Config } from './store.js';
import { objectVersion } from './authority.js';
import { analyticalContext } from './investigation.js';
import { createMcpServer } from './mcp.js';
import { verifyAcceptanceEvidence } from './acceptance-evidence.js';
import {search,brief} from './query.js';
import { handleHook, loadJournal, debt } from './hooks.js';

const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'ledger-investigation-'));
process.env.LEDGER_CONFIG_DIR=path.join(tmp,'.ledger');
process.env.LEDGER_GIT_SYNC='0';
const cfg:Config={ledger_dir:path.join(tmp,'ledger'),author:'agaaz',git_sync:false};
initLedger(cfg.ledger_dir,'agaaz');
const scope={product:'HiAstro-fixture',dataset:'frozen-events',environment:'test',metric:'trial_rate',population:'eligible Android users',grain:'user',attribution_rule:'within seven days of first exposure'};
const def=(title:string,formula:string,extra:Record<string,unknown>={})=>record(cfg,{type:'definition',fields:{title,metric:'trial_rate',formula,source:'fixture',owner:'agaaz',valid_from:'2026-08-01',analysis_scope:scope,...extra}});
const d1=def('Original denominator','trial starts / impression events');
const old=getById(cfg,d1.id)!;
const finding=record(cfg,{type:'finding',fields:{title:'Original trial comparison',question:'Compare trial conversion',result:'Original value needs validation',source:'fixture',data_window:{from:'2026-08-01',to:'2026-08-07'},inputs:[{source:'fixture'}],method:'Compute the rate using the exact stored denominator.',assumptions:[{statement:'The frozen fixture is complete',kind:'implicit'}],analysis_scope:scope,definitions_used:['trial_rate'],dependencies:[{relation:'uses-definition',id:d1.id,version:objectVersion(old)}],query:'SELECT count(*) FROM events'}});
const downstream=record(cfg,{type:'finding',fields:{title:'Revenue projection from trial assumptions',question:'What revenue might this conversion imply?',result:'Projection awaits validation',source:'fixture',data_window:{from:'2026-08-01',to:'2026-08-07'},inputs:[{source:'fixture'}],method:'Use the original trial comparison as an input to a qualitative projection',assumptions:[{statement:'The conversion input applies to this projection',kind:'implicit'}],dependencies:[{relation:'derived-from',id:finding.id,version:objectVersion(getById(cfg,finding.id)!)}]}});
const acceptance={actor:'agaaz',accepted_at:'2026-09-10',expected_predecessor:{id:d1.id,version:objectVersion(old)},evidence_refs:[{artifact_id:d1.id,sha256:objectVersion(old),role:'review'}]};
const d2=def('Corrected unique-user denominator','trial users / eligible unique users',{supersedes:d1.id,acceptance,correction:{effect:'historical',reason:'Repeated impressions are not distinct eligible users'}});
const accepted=getById(cfg,d2.id)!;
for(let i=0;i<20;i++) def(`Newest conversion claim ${i}`,'incorrect denominator',{status:'draft'});
def('Other product same named metric','irrelevant formula',{analysis_scope:{...scope,product:'unrelated-product'}});
const pack=analyticalContext(loadAll(cfg),{question:'Compare trial conversion',scope:{...scope,window:{from:'2026-09-01',to:'2026-09-07'}},definition_ids:[d1.id,d2.id],limit:1});
assert.ok(pack.current.some(o=>o.id===d2.id),'mandatory accepted definition survives draft crowding');
assert.ok(pack.affected.some(o=>o.id===finding.id),'historical affected result retained outside current task window');
assert.ok(pack.affected.some(o=>o.id===downstream.id),'exact downstream impact is retained even without matching analytical scope');
assert.ok(!pack.current.some(o=>o.fields.formula==='incorrect denominator'));
assert.ok(!pack.objects.some(o=>o.fields.analysis_scope && (o.fields.analysis_scope as any).product==='unrelated-product'));
assert.ok(pack.text.includes('Results requiring review'));
assert.ok(pack.text.includes(objectVersion(accepted)));
const unspecifiedObjects=loadAll(cfg).map(o=>{
  if(o.id!==d2.id) return o;
  const {correction: _correction,...fields}=o.fields; return {...o,fields};
});
const unspecified=analyticalContext(unspecifiedObjects,{question:'trial conversion',scope,definition_ids:[d1.id]});
assert.ok(unspecified.affected.some(o=>o.id===finding.id),'missing effect metadata cannot hide downstream obligations');
assert.ok(unspecified.impacts.some(i=>!i.complete && i.effect==='unspecified'));

const intervalScope={...scope,metric:'bounded_trial_rate'};
const i1=record(cfg,{type:'definition',fields:{title:'Bounded period trial rate',metric:intervalScope.metric,formula:'trial users / exposed users',source:'fixture',owner:'agaaz',valid_from:'2026-08-01',analysis_scope:{...intervalScope,window:{from:'2026-08-01',to:'2026-08-10'}}}});
const i1obj=getById(cfg,i1.id)!;
record(cfg,{type:'definition',fields:{title:'Bounded period reviewed trial rate',metric:intervalScope.metric,formula:'trial users / eligible users',source:'fixture',owner:'agaaz',valid_from:'2026-08-01',analysis_scope:{...intervalScope,window:{from:'2026-08-01',to:'2026-08-10'}},supersedes:i1.id,acceptance:{actor:'agaaz',accepted_at:'2026-09-10',expected_predecessor:{id:i1.id,version:objectVersion(i1obj)},evidence_refs:[{artifact_id:i1.id,sha256:objectVersion(i1obj),role:'review'}]},correction:{effect:'historical',reason:'Exact historical window review'}}});
const intervalQuery={...intervalScope,window:{from:'2026-08-01',to:'2026-08-31'}};
const intervalHits=search(cfg,'Bounded period trial rate',{scope:intervalQuery});
assert.ok(intervalHits.length && intervalHits.every(h=>h.authority_status==='unavailable'),'partial applicability returns explicit unavailable evidence rather than empty search');
assert.match(brief(cfg,{scope:intervalQuery}),/no single accepted definition applies throughout/);
const intervalPack=analyticalContext(loadAll(cfg),{question:'bounded trial rate',scope:intervalQuery});
assert.ok(intervalPack.resolutions.some(r=>r.status==='unavailable'));
assert.match(intervalPack.text,/split the analysis window/);

await verifyAcceptanceEvidence(cfg,{acceptance});
await assert.rejects(verifyAcceptanceEvidence(cfg,{acceptance:{...acceptance,evidence_refs:[{artifact_id:d1.id,sha256:'f'.repeat(64),role:'review'}]}}),/version mismatch/);
await assert.rejects(verifyAcceptanceEvidence(cfg,{acceptance:{...acceptance,evidence_refs:[{sha256:'f'.repeat(64),role:'review'}]}}),/unavailable/);
await assert.rejects(verifyAcceptanceEvidence(cfg,{acceptance:{...acceptance,evidence_refs:[{artifact_id:d1.id,sha256:objectVersion(old),role:'review',session_id:'fabricated-session',seq:123}]}}),/event coordinates/);

const server=createMcpServer(cfg);
const client=new Client({name:'investigation-test',version:'1'});
const [a,b]=InMemoryTransport.createLinkedPair();await server.connect(a);await client.connect(b);
const resolved=await client.callTool({name:'ledger_get',arguments:{id:d1.id}});
assert.ok(JSON.stringify(resolved).includes(d2.id),'get old evidence includes applicable correction');
const retrieved=await client.callTool({name:'ledger_investigation',arguments:{question:'trial conversion',analysis_scope:scope,limit:1}});
assert.ok(!retrieved.isError,JSON.stringify(retrieved));
assert.ok(JSON.stringify(retrieved).includes(d2.id));
const impact=await client.callTool({name:'ledger_impact',arguments:{correction_id:d2.id}});
assert.ok(JSON.stringify(impact).includes(finding.id));
const invalidDate=await client.callTool({name:'ledger_get',arguments:{id:d1.id,as_of:'2026-02-31'}});
assert.ok(invalidDate.isError,'invalid calendar dates fail validation');

const sid='mcp-scoped-obligation';
for(const id of ['a','b']) handleHook('PostToolUse',{session_id:sid,tool_name:'mcp__mixpanel__query',tool_use_id:id,tool_input:{sql:`select '${id}'`},tool_response:{result:[]}});
const before=debt(loadJournal(sid));assert.equal(before.length,2);
const save=await client.callTool({name:'ledger_record_finding',arguments:{title:'A covered query only',question:'What did query A establish?',result:'Synthetic evidence A retained',source:'fixture',data_window:{from:'2026-09-10',to:'2026-09-10'},inputs:[{source:'fixture'}],method:'Inspect only the explicit synthetic A result.',assumptions:[{statement:'The fixture represents its declared input',kind:'implicit'}],capture_coverage:[{session_id:sid,evidence_ids:[before[0].evidence_id!]}]}});
assert.ok(!save.isError,JSON.stringify(save));
assert.equal(debt(loadJournal(sid)).length,1,'MCP acknowledgment covers A only even without wrapper hooks');
const skip=await client.callTool({name:'ledger_skip_record',arguments:{reason:'Unrelated exploratory thought'}});
assert.ok(!skip.isError);assert.equal(debt(loadJournal(sid)).length,1,'unscoped skip cannot clear B');
await client.close();await server.close();
console.log('selftest-investigation: passed scoped correction retrieval, affected history, exact evidence validation and MCP coverage integration');
