import fs from "node:fs";
import path from "node:path";
import matter from "gray-matter";
import { DIRS, TYPES, type LedgerObject, type LedgerType } from "./schema.js";
import type { Config } from "./store.js";

/**
 * Derived files, rebuilt from the full object set on every record. They are a
 * pure function of (objects, today), never edited, and never merged: when two
 * machines' commits collide on one of these, conflict resolution just
 * regenerates it. Keep it that way; anything stateful here (append-only logs,
 * wall-clock stamps) reintroduces conflicts.
 */

const NOTE = "<!-- generated by `ledger`; do not edit -->";

/** Repo-relative path of a file this module owns. */
export function isGeneratedView(relPath: string): boolean {
  const p = relPath.split(path.sep).join("/");
  if (p === "README.md" || p === "index.md" || p === "log.md") return true;
  return Object.values(DIRS).some((d) => p === `${d}/index.md`);
}

function rel(o: LedgerObject, from: string): string {
  return path.relative(from, o.path).split(path.sep).join("/");
}

function line(o: LedgerObject, from: string): string {
  return `* [${o.title}](${rel(o, from)}) - ${o.description || ""}`;
}

/** Newest first, id as tiebreak, so every machine emits identical bytes. */
function ordered(all: LedgerObject[]): LedgerObject[] {
  return [...all].sort((a, b) =>
    a.created < b.created ? 1 : a.created > b.created ? -1 : a.id < b.id ? -1 : 1
  );
}

/** Date the ledger was created, stamped into LEDGER.md frontmatter by `init`. */
function initDate(cfg: Config): string | undefined {
  try {
    const c = matter(fs.readFileSync(path.join(cfg.ledger_dir, "LEDGER.md"), "utf8")).data.created;
    if (c) return (c instanceof Date ? c.toISOString() : String(c)).slice(0, 10);
  } catch {
    /* no LEDGER.md */
  }
  return undefined;
}

/** OKF §8: per-directory index.md, plus a root index.md with okf_version. */
function writeIndexes(cfg: Config, all: LedgerObject[]): string[] {
  const out: string[] = [];
  const root = cfg.ledger_dir;

  for (const t of TYPES) {
    const dir = path.join(root, DIRS[t]);
    fs.mkdirSync(dir, { recursive: true });
    const objs = all.filter((o) => o.type === t);
    const stable = objs.filter((o) => o.status === "stable");
    const sections: [string, LedgerObject[]][] = [
      ["Draft", objs.filter((o) => o.status === "draft")],
      ["Deprecated", objs.filter((o) => o.status === "deprecated")],
    ];
    const md = [
      `# ${DIRS[t]}`,
      ``,
      ...(stable.length ? stable.map((o) => line(o, dir)) : ["* (none yet)"]),
      ...sections.flatMap(([h, xs]) => (xs.length ? [``, `# ${h}`, ``, ...xs.map((o) => line(o, dir))] : [])),
      ``,
    ].join("\n");
    const f = path.join(dir, "index.md");
    fs.writeFileSync(f, md);
    out.push(f);
  }

  const rootIndex = [
    `---`,
    `okf_version: "0.2"`,
    `---`,
    `# Ledger`,
    ``,
    `* [How this ledger works](LEDGER.md) - the four object types and the rules`,
    ...TYPES.map((t) => {
      const n = all.filter((o) => o.type === t && o.status === "stable").length;
      return `* [${DIRS[t]}](${DIRS[t]}/) - ${n} ${t}${n === 1 ? "" : "s"} in force`;
    }),
    `* [log](log.md) - newest first`,
    ``,
  ].join("\n");
  const f = path.join(root, "index.md");
  fs.writeFileSync(f, rootIndex);
  out.push(f);
  return out;
}

/** OKF §9: log.md, date-grouped, newest first. Rebuilt from the objects, not appended. */
function writeLog(cfg: Config, all: LedgerObject[]): string {
  const f = path.join(cfg.ledger_dir, "log.md");
  const byDay = new Map<string, string[]>();
  const add = (day: string, entry: string) => {
    if (!byDay.has(day)) byDay.set(day, []);
    byDay.get(day)!.push(entry);
  };
  for (const o of all) {
    const kind = o.supersedes ? "Supersede" : "Creation";
    add(
      o.created.slice(0, 10) || "undated",
      `* **${kind}**: ${o.type} [${o.title}](${rel(o, cfg.ledger_dir)}) by ${o.author}${o.supersedes ? ` (replaces ${o.supersedes})` : ""}.`
    );
  }
  const oldest = [...byDay.keys()].sort()[0];
  add(initDate(cfg) ?? oldest ?? new Date().toISOString().slice(0, 10), `* **Initialization**: Created the ledger.`);

  const md = [`# Ledger log`, ``];
  for (const day of [...byDay.keys()].sort().reverse()) md.push(`## ${day}`, ...byDay.get(day)!, ``);
  fs.writeFileSync(f, md.join("\n"));
  return f;
}

/** Root README.md: what a human sees on GitHub. Same content as the agent brief. */
function writeReadme(cfg: Config, all: LedgerObject[]): string {
  const root = cfg.ledger_dir;
  const stable = all.filter((o) => o.status === "stable");
  const since = new Date(Date.now() - 14 * 86_400_000).toISOString();
  const byType = (t: LedgerType) => stable.filter((o) => o.type === t);
  const recent = (t: LedgerType) => byType(t).filter((o) => o.created >= since);
  const link = (o: LedgerObject) => `[${o.id}](${rel(o, root)})`;
  const esc = (s: unknown) => String(s ?? "").replace(/\|/g, "\\|").replace(/\n/g, " ");

  const defs = byType("definition");
  const decs = byType("decision");
  const chgs = recent("change");
  const fnds = recent("finding");
  // stamp from the data, not the clock, so regenerating on another machine is a no-op
  const last = all[0]?.created ? `Last record ${all[0].created.slice(0, 16).replace("T", " ")} UTC.` : `No records yet.`;

  const md: string[] = [
    `---`,
    `type: Reference`,
    `title: Ledger dashboard`,
    `description: Generated view of definitions, decisions in force, and the last 14 days of changes and findings.`,
    `---`,
    NOTE,
    `# Ledger`,
    ``,
    `${last} ${defs.length} definitions, ${decs.length} decisions in force, ${chgs.length} changes and ${fnds.length} findings in the last 14 days. [How this works](LEDGER.md) · [Log](log.md)`,
    ``,
    `## Definitions`,
    ``,
  ];
  if (defs.length) {
    md.push(`| metric | formula | source | excludes | owner | since | id |`, `|---|---|---|---|---|---|---|`);
    for (const o of defs) {
      const f = o.fields;
      md.push(`| **${esc(f.metric)}** | ${esc(f.formula)} | ${esc(f.source)} | ${esc((f.exclusions as string[])?.join(", "))} | ${esc(f.owner)} | ${esc(f.valid_from)} | ${link(o)} |`);
    }
  } else md.push(`_none yet_`);

  md.push(``, `## Decisions in force`, ``);
  if (decs.length) {
    md.push(`| decision | rationale | confidence | owner | since | revisit | id |`, `|---|---|---|---|---|---|---|`);
    for (const o of decs) {
      const f = o.fields;
      md.push(`| **${esc(f.decision)}** | ${esc(f.rationale)} | ${esc(f.confidence)} | ${esc(f.owner)} | ${esc(f.valid_from)} | ${esc(f.revisit_by ?? "")} | ${link(o)} |`);
    }
  } else md.push(`_none_`);

  md.push(``, `## Changes, last 14 days`, ``);
  if (chgs.length) {
    md.push(`| shipped | what | surface | scope | owner | id |`, `|---|---|---|---|---|---|`);
    for (const o of chgs) {
      const f = o.fields;
      md.push(`| ${esc(f.shipped_at)} | **${esc(f.what)}** | ${esc(f.surface)} | ${esc(f.scope ?? "")} | ${esc(f.owner)} | ${link(o)} |`);
    }
  } else md.push(`_none_`);

  md.push(``, `## Findings, last 14 days`, ``);
  if (fnds.length) {
    md.push(`| date | question | result | window | definitions | by | id |`, `|---|---|---|---|---|---|---|`);
    for (const o of fnds) {
      const f = o.fields;
      const w = f.data_window as any;
      md.push(`| ${o.created.slice(0, 10)} | **${esc(f.question)}** | ${esc(f.result)} | ${esc(w?.from)}→${esc(w?.to)} | ${esc((f.definitions_used as string[])?.join(", "))} | ${esc(o.author)} | ${link(o)} |`);
    }
  } else md.push(`_none_`);

  // Every draft, labeled by origin. Not in force; shown so nothing sits unseen.
  const drafts = all.filter((o) => o.status === "draft");
  if (drafts.length) {
    md.push(``, `## Drafts, not in force (${drafts.length})`, ``, `Fallback drafts were extracted from transcripts after live capture failed. Manual drafts were recorded with status: draft by a person or their agent. Neither is in force until someone records a stable object with \`supersedes\`, or discards.`, ``);
    md.push(`| origin | type | title | note | by | id |`, `|---|---|---|---|---|---|`);
    for (const o of drafts) {
      const fb = o.fields.capture_method === "transcript_fallback";
      md.push(`| ${fb ? "fallback" : "manual"} | ${o.type} | **${esc(o.title)}** | ${esc(fb ? o.fields.capture_reason ?? "" : "")} | ${esc(o.author)} | ${link(o)} |`);
    }
  }
  md.push(``);

  const f = path.join(root, "README.md");
  fs.writeFileSync(f, md.join("\n"));
  return f;
}

/** Rebuild every derived file from the object set. Returns the paths written, for git add. */
export function regenerateViews(cfg: Config, all: LedgerObject[]): string[] {
  const objs = ordered(all);
  return [...writeIndexes(cfg, objs), writeLog(cfg, objs), writeReadme(cfg, objs)];
}
